### ISSUE TITLE
initial setup seems to be looking for AWS Creds

### ISSUE THREAD

**Issue by wolfspyre** [taylorgoolsby/cobalt#2]
Hi there!
Cool stuff!
```
/Users/Shared/MLModels/Cobalt/cobalt$ npm install
```
...
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cobalt@1.0.0',
npm WARN EBADENGINE   required: { node: '18' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }
```
...
```
...
/Users/Shared/MLModels/Cobalt/cobalt$ npm start
> cobalt@1.0.0 start
> rebuild -w src/common -w src/backend -w src/api -w src/cloud -w src/mysql --output build --transform 'src/*/{!(node_modules),node_modules/common}/**/*.{js,mjs}' --using scripts/transformer.js --fork build/backend/src/schema/generateSchema.js --fork build/backend/src/email/startLocalEmailServer.js --fork build/mysql/src/localStart.js --fork build/backend/src/start.js -k 3306 -k 4000 -k 5555
```
...
```
[monitor] fork build/backend/src/start.js
[monitor] timeout SIGRES build/backend/src/schema/generateSchema.js
[monitor] timeout SIGRES build/backend/src/email/startLocalEmailServer.js
[monitor] crash build/backend/src/email/startLocalEmailServer.js
[monitor] crash build/backend/src/schema/generateSchema.js
[monitor] restarting...
[monitor] SIGRES build/backend/src/start.js
[monitor] restarting...
[monitor] SIGRES build/backend/src/start.js
[monitor] timeout SIGRES build/backend/src/start.js
[monitor] crash build/backend/src/start.js
[monitor] fork build/backend/src/schema/generateSchema.js
[monitor] fork build/backend/src/email/startLocalEmailServer.js
[monitor] fork build/mysql/src/localStart.js
[monitor] restarting...
[monitor] SIGRES build/backend/src/schema/generateSchema.js
[monitor] SIGRES build/backend/src/email/startLocalEmailServer.js
[monitor] SIGRES build/mysql/src/localStart.js
[monitor] fork build/backend/src/start.js
/Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13
    throw new property_provider_1.CredentialsProviderError("Could not load credentials from any providers", false);
          ^

CredentialsProviderError: Could not load credentials from any providers
    at /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24
    at async file:///Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/src/loadAwsCredentials.js:17:21 {
  tryNextLink: false
}

Node.js v21.7.1
[monitor] crash build/backend/src/email/startLocalEmailServer.js
[monitor] timeout SIGRES build/backend/src/schema/generateSchema.js
[monitor] timeout SIGRES build/mysql/src/localStart.js
[monitor] crash build/mysql/src/localStart.js
[monitor] crash build/backend/src/schema/generateSchema.js
(node:87889) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13
    throw new property_provider_1.CredentialsProviderError("Could not load credentials from any providers", false);
          ^

CredentialsProviderError: Could not load credentials from any providers
    at /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async /Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24
    at async file:///Users/Shared/MLModels/Cobalt/cobalt/build/backend/node_modules/common/src/loadAwsCredentials.js:17:21 {
  tryNextLink: false
}

Node.js v21.7.1
[monitor] crash build/backend/src/start.js
^C[monitor] killed port 3306
[monitor] killed port 4000
[monitor] killed port 5555
[monitor] stopped
```
it seems odd that there's be any sort of dependency on anything cloudy whatsoever, given this is supposed to be entirely self-contained, yes? 

Any ideas?

**Comment by taylorgoolsby** [comment]
Thanks for catching that. This boilerplate for this project was copies from another project which was using AWS parts. This project does indeed run locally and doesn't use any AWS. 

I'll have to give it a closer look, but to unblock you, you can try removing this line: https://github.com/taylorgoolsby/cobalt/blob/master/src/common/src/Config.js#L6

And about the Unsupported engine, try installing node 18 using nvm.

**Comment by wolfspyre** [comment]
hmm....

seems 
`build/backend/node_modules/common/src/Config.js:64` also has a minor needed tweak 

which it looks like comes from `src/common/src/Config.js`

`if (isLocal && !credentials.accessKeyId)` 

seems like `if (credentials && isLocal && !credentials.accessKeyId)` bypasses the undef error due to credentials not existing, but not sure if that's the only one yet..... have't yet managed to get things to load.

**NOPE** :) but you prolly knew that... will have to do some more poking 




It seems odd to expect people to have an old version of node installed tho.... 
admittedly, I'm not much of a node fan or user; 
but 20.x is LTS; 
21.x is latest...
is there a legit reason to downgrade?

`nvm` isn't installed/present...  is that a requirement? 

Not trying to be obtuse.... the other projects I use which necessitate node installed require >20.x and I'm somewhat  reticent to get stuck in an odd node package hell with conflicting versions installed..


will report back if things work one way or the other... trying to load the webui still returns an error, but it could be that the backend hasn't finished initializing yet.

**Comment by taylorgoolsby** [comment]
This of a local project so the other if branch will never hit. 

For the node version, using nvm is recommended. Install a version 18 using nvm. I will add a .nvm file to the project if there isn't one yet and this will cause your nvm to automatically switch to version 18.
